### ISSUE TITLE
animation:setLooping

### ISSUE THREAD

**Issue by ghost** [davisdude/Walt#2]
animation:setLooping will always set it to true
because:
```looping = looping or true```
if it == false then "or" set it to true.

So it probably should look like:
```setLooping = function( self, looping )
err( 'setLooping: expected argument two to be a boolean, got %type%.', looping, 'boolean' )
    if not looping then
       looping = false
    else
       looping = true
    end
 self.looping = looping
end
```

**Comment by davisdude** [comment]
Good catch! Surprised it took so long to notice something so simple.

**Comment by ghost** [comment]
I think it's because not really much people use this library (because stars doesn't mean, that someone actually use library...) and instead use https://github.com/kikito/anim8 since it more popular...
Anyway, good job and thanks for fix!
I will continue build game with it and if i found something else, i will tell.
